version: '3'
services:
  short-url-app:
    image: short-url-app
    build: .
    stdin_open: true
    tty: true
    command: bin/rails server --port 3000 --binding 0.0.0.0
    env_file: ./dev.env
    ports:
    - "3000:3000"
    depends_on:
    - postgres
    working_dir: /app
    volumes:
    - .:/app
    networks:
    - app

  worker:
    image: short-url-app
    command: bundle exec rake resque:work
    env_file: ./dev.env
    working_dir: /app
    volumes:
    - .:/app:cached
    depends_on:
    - postgres
    networks:
    - app

  postgres:
    image: postgres
    container_name: short_url_postgres_dev
    volumes:
    - data-postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=root
    ports:
    - 5432:5432/tcp
    networks:
    - app

volumes:
  data-postgres:
    driver: local

networks:
  app: