default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Short_Url_development

test:
  <<: *default
  database: Short_Url_test

production:
  <<: *default
  database: Short_Url_production
  username: Short_Url
  password: <%= ENV['SHORTER_URL_DATABASE_PASSWORD'] %>
