default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: postgres

development:
  <<: *default
  database: Short_Url_development

test:
  <<: *default
  database: Short_Url_development_test
  host: postgres_rspec

production:
  <<: *default
  database: Short_Url_development
